#!/usr/bin/env python3
"""
run.py — RoarPass workflow entrypoint and phase state machine.

Usage:
  python orchestrator/run.py --prd docs/RoarPass_PRD.md      # run from Phase 0; halts at Phase 2 gate
  python orchestrator/run.py --resume --approve              # resume into Phase 3
  python orchestrator/run.py --resume --revise "feedback"    # re-run design refine/review with feedback
  python orchestrator/run.py --resume --revise-full "fb"     # re-run design from chunking
  python orchestrator/run.py --status                        # print current state

Secrets (ANTHROPIC_API_KEY, GITHUB_*) are read from the environment / .env. Nothing is
hard-coded and nothing secret is committed.

This file is the conductor. Each phase's detailed contract lives in phases/*.md and is passed
to the relevant agents; the heavy per-phase logic is implemented in phase_runners below, which
follow those specs. Kept deliberately readable so Claude Code can extend it.
"""
from __future__ import annotations
import argparse
import json
import os
import pathlib
import sys

import yaml

# load .env if present (no external dep: simple parser)
_ROOT = pathlib.Path(__file__).resolve().parent.parent


def _load_dotenv():
    f = _ROOT / ".env"
    if f.exists():
        for line in f.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            os.environ.setdefault(k.strip(), v.strip())


_load_dotenv()

from orchestrator import agent, fanout, git_ops, gate, runlog, executor, notify  # noqa: E402

_WF = yaml.safe_load((_ROOT / "config" / "workflow.yaml").read_text())
_STATE = _ROOT / "state" / "run_state.json"
# The PRODUCT repo Claude Code builds into (separate from this workflow bundle):
PRODUCT = _ROOT.parent / "roarpass"


# ----------------------------- state helpers --------------------------------
def load_state() -> dict:
    if _STATE.exists():
        return json.loads(_STATE.read_text())
    return {"phase": -1, "status": "init", "chunks": None}


def save_state(st: dict):
    _STATE.write_text(json.dumps(st, indent=2))


def phase_spec(pid: int) -> str:
    spec_path = _ROOT / next(p["spec"] for p in _WF["phases"] if p["id"] == pid)
    return spec_path.read_text()


def preflight():
    """Validate secrets + a cheap API call before doing real work (Phase 0 step 2)."""
    for var in ("ANTHROPIC_API_KEY", "GITHUB_TOKEN", "GITHUB_USER", "GITHUB_REPO"):
        if not os.environ.get(var):
            sys.exit(f"Missing required env var: {var}. Copy .env.example to .env and fill it in.")
    # cheap validation: a tiny agent call
    try:
        agent.run_agent("orchestrator", "Reply with the single word: OK", max_tokens=8)
    except Exception as e:  # noqa: BLE001
        sys.exit(f"Anthropic API key validation failed: {e}")
    print("[preflight] secrets present, API key valid.")


# ----------------------------- phase runners --------------------------------
# Each runner implements the contract in phases/phaseN_*.md. They are intentionally compact;
# the full agent instructions live in agents/*.md and are loaded by agent.run_agent.

def run_phase0(st: dict):
    print("== Phase 0: bootstrap ==")
    runlog.log_phase(0, "bootstrap", "running")
    preflight()
    PRODUCT.mkdir(exist_ok=True)
    # scaffold (delegated to a quick orchestrator-authored layout)
    for d in ("docs", "apps/web", "apps/api", "packages/shared", "data/seed", "tests", "demo"):
        (PRODUCT / d).mkdir(parents=True, exist_ok=True)
    (PRODUCT / "README.md").write_text("# RoarPass\n\nGenerated by the RoarPass build workflow.\n")
    (PRODUCT / ".gitignore").write_text((_ROOT / ".gitignore").read_text())
    # copy the PRD into the product repo for agents to reference
    prd_src = pathlib.Path(st["prd"])
    (PRODUCT / "docs" / "RoarPass_PRD.md").write_text(prd_src.read_text())
    _git_init_if_needed()
    git_ops.commit_and_push(PRODUCT, _git_msg("phase0"))
    runlog.log_git("push", _git_msg("phase0"))
    st.update(phase=0, status="complete")
    runlog.log_phase(0, "bootstrap", "complete")
    save_state(st)


def run_phase1(st: dict):
    print("== Phase 1: requirement refinement ==")
    runlog.log_phase(1, "requirements", "running")
    prd = (PRODUCT / "docs" / "RoarPass_PRD.md").read_text()
    fan = _WF["fanout"]

    # Stage 1: chunk
    chunk_raw = agent.run_agent(
        "req_chunker",
        f"min_chunks={fan['min_chunks']} max_chunks={fan['max_chunks']}\n\nPRD:\n{prd}",
        phase=1, agent_id="req_chunker")
    chunks = json.loads(agent.parse_json(chunk_raw))["chunks"]
    (PRODUCT / "docs/requirements").mkdir(parents=True, exist_ok=True)
    (PRODUCT / "docs/requirements/chunks.json").write_text(json.dumps({"chunks": chunks}, indent=2))
    st["chunks"] = chunks

    # Stage 2+3: explore + consistency review loop
    worker_tasks = [{
        "id": c["slug"],
        "prompt": (f"Chunk:\n{json.dumps(c, indent=2)}\n\nFull chunk list:\n"
                   f"{json.dumps(chunks, indent=2)}\n\nRelevant PRD:\n{prd}")
    } for c in chunks]

    def reviewer_prompt(outputs):
        specs = "\n\n".join(
            f"### {o['id']}\n" + "\n".join(c for _, c in o["files"]) for o in outputs)
        return (f"chunks.json:\n{json.dumps(chunks, indent=2)}\n\nAll specs:\n{specs}\n\n"
                "Review for cross-chunk consistency and PRD coverage.")

    verdict = fanout.review_loop(
        worker_role="req_explorer", reviewer_role="req_consistency_reviewer",
        repo_dir=PRODUCT, worker_tasks=worker_tasks, reviewer_prompt_fn=reviewer_prompt,
        max_rounds=_WF["quality_loops"]["requirements_max_rounds"], phase=1)

    _assemble_refined_requirements(chunks)
    print(f"[phase1] consistency signed_off={verdict.get('signed_off')}")
    git_ops.commit_and_push(PRODUCT, _git_msg("phase1"),
                            branch=_git_branch("requirements_branch"))
    git_ops.commit_and_push(PRODUCT, _git_msg("phase1"))  # also to main
    runlog.log_git("push", _git_msg("phase1"))
    st.update(phase=1, status="complete")
    runlog.log_phase(1, "requirements", "complete")
    save_state(st)


def run_phase2(st: dict, revise: str = "", full: bool = False):
    print("== Phase 2: UX/UI design ==")
    runlog.log_phase(2, "design", "running")
    refined = (PRODUCT / "docs/requirements/REFINED_REQUIREMENTS.md").read_text()
    chunks = st["chunks"]

    pages_file = PRODUCT / "docs/design/pages.json"
    if full or not pages_file.exists():
        # Stage 1: design chunk
        pr = agent.run_agent("design_chunker",
                             f"REFINED_REQUIREMENTS:\n{refined}\n\nchunks:\n{json.dumps(chunks)}",
                             phase=2, agent_id="design_chunker")
        pages = json.loads(agent.parse_json(pr))["pages"]
        pages_file.parent.mkdir(parents=True, exist_ok=True)
        pages_file.write_text(json.dumps({"pages": pages}, indent=2))
        # Stage 2 assets (once)
        assets = agent.run_agent("asset_designer",
                                 f"Design system for RoarPass.\nReqs:\n{refined[:4000]}",
                                 design=True, phase=2, agent_id="asset_designer")
        fanout.write_files(PRODUCT, agent.parse_files(assets))
    else:
        pages = json.loads(pages_file.read_text())["pages"]

    tokens = (PRODUCT / "docs/design/tokens.css")
    tokens_txt = tokens.read_text() if tokens.exists() else ""

    worker_tasks = [{
        "id": p["slug"],
        "prompt": (f"Page:\n{json.dumps(p, indent=2)}\n\nShared tokens.css:\n{tokens_txt}\n\n"
                   + (f"Human revision request to honor:\n{revise}\n\n" if revise else "")
                   + "Design desktop + mobile HTML.")
    } for p in pages]

    def reviewer_prompt(outputs):
        listing = "\n".join(f"- {o['id']}: {[f for f,_ in o['files']]}" for o in outputs)
        return (f"pages.json:\n{json.dumps(pages)}\n\nDesigned pages:\n{listing}\n\n"
                "Review a window of pages for quality, usability, a11y, token consistency.")

    fanout.review_loop(
        worker_role="page_designer", reviewer_role="design_refiner", repo_dir=PRODUCT,
        worker_tasks=worker_tasks, reviewer_prompt_fn=reviewer_prompt,
        max_rounds=_WF["quality_loops"]["design_max_rounds"], design=True, phase=2)

    # Stage 4: system review
    sysrev = agent.run_agent("design_system_reviewer",
                             f"pages.json:\n{json.dumps(pages)}\n\nReview whole-product coherence.",
                             phase=2, agent_id="design_system_reviewer")
    fanout.write_files(PRODUCT, agent.parse_files(sysrev))

    # Stage 5: screenshots + README
    _capture_screens(pages)
    _assemble_design_readme(pages)

    git_ops.commit_and_push(PRODUCT, _git_msg("phase2"), branch=_git_branch("design_branch"))
    runlog.log_git("push", _git_msg("phase2"), branch=_git_branch("design_branch"))
    st.update(phase=2, status="awaiting_approval")
    runlog.log_phase(2, "design", "awaiting_approval")
    runlog.log_gate("awaiting_approval")
    save_state(st)
    gate.raise_gate(PRODUCT)  # <<< the single mandatory human gate


def run_phase3(st: dict):
    print("== Phase 3: implementation + deploy ==")
    runlog.log_phase(3, "implementation", "running")
    chunks = st["chunks"]
    waves = _topo_waves(chunks)
    refined = (PRODUCT / "docs/requirements/REFINED_REQUIREMENTS.md").read_text()

    for wi, wave in enumerate(waves):
        print(f"[phase3] build wave {wi+1}/{len(waves)}: {[c['slug'] for c in wave]}")
        worker_tasks = [{
            "id": c["slug"],
            "prompt": (f"Implement chunk:\n{json.dumps(c, indent=2)}\n\nRefined reqs:\n{refined}\n\n"
                       "Match approved design under apps/web/design/. Write tests.")
        } for c in wave]

        def reviewer_prompt(outputs):
            return ("Review these chunk implementations for correctness, security, design "
                    "fidelity, and acceptance criteria:\n"
                    + "\n".join(f"- {o['id']}" for o in outputs))

        fanout.review_loop(
            worker_role="coder", reviewer_role="code_reviewer", repo_dir=PRODUCT,
            worker_tasks=worker_tasks, reviewer_prompt_fn=reviewer_prompt,
            max_rounds=_WF["quality_loops"]["code_review_max_rounds"], phase=3)

        # merge each chunk in the wave, commit per feature
        for c in wave:
            merge_raw = agent.run_agent(
                "merge_agent", f"Integrate chunk {c['slug']} into main; resolve conflicts.",
                phase=3, agent_id=f"merge:{c['slug']}")
            fanout.write_files(PRODUCT, agent.parse_files(merge_raw))
            git_ops.commit_and_push(
                PRODUCT, _git_msg("phase3_feature", chunk=c["slug"], chunk_title=c["title"]))
            runlog.log_git("push", _git_msg("phase3_feature", chunk=c["slug"],
                                            chunk_title=c["title"]))

    # Stage 4: deploy + parallel checks
    dep = agent.run_agent("deploy_agent", "Produce local deploy plan + parallel smoke checks; "
                                          "derive deps from the actual stack.",
                          phase=3, agent_id="deploy_agent")
    fanout.write_files(PRODUCT, agent.parse_files(dep))
    _run_local_deploy_and_checks()

    git_ops.commit_and_push(PRODUCT, _git_msg("phase3_final"))
    git_ops.tag_and_push(PRODUCT, "v0.1.0-demo")
    runlog.log_git("push", _git_msg("phase3_final"))
    st.update(phase=3, status="complete")
    runlog.log_phase(3, "implementation", "complete")
    save_state(st)


def run_phase4(st: dict):
    print("== Phase 4: data seeding, testing, demo ==")
    runlog.log_phase(4, "data_testing_demo", "running")
    chunks = st["chunks"]

    # Stage 1: seed (synthetic)
    seed = agent.run_agent("data_seeder", "Generate synthetic FIFA WC 2026 (+ small Club WC) seed.",
                           phase=4, agent_id="data_seeder")
    fanout.write_files(PRODUCT, agent.parse_files(seed))

    # Stage 2: parallel tests per area
    test_tasks = [{
        "id": c["slug"],
        "prompt": f"Write+run functional+integration tests for area:\n{json.dumps(c)}"
    } for c in chunks]
    results = fanout.parallel_map("test_agent", test_tasks, phase=4)
    for r in results:
        fanout.write_files(PRODUCT, r["files"])
    _consolidate_test_report(results)

    # Stage 3: demo
    demo = agent.run_agent("demo_agent", "Produce 3-4 page demo presentation + capture spec for "
                                         "the South Korea WC 2026 flagship journey.",
                           phase=4, agent_id="demo_agent")
    fanout.write_files(PRODUCT, agent.parse_files(demo))
    _run_demo_capture()

    git_ops.commit_and_push(PRODUCT, _git_msg("phase4"))
    runlog.log_git("push", _git_msg("phase4"))
    st.update(phase=4, status="complete")
    runlog.log_phase(4, "data_testing_demo", "complete")
    save_state(st)
    print("\n*** Phase 4 complete. Product demo in roarpass/demo/. ***\n")


def run_phase5(st: dict):
    """Render the 'how we built it' animation from the real run log, for slides."""
    print("== Phase 5: build-story animation ==")
    runlog.log_phase(5, "build_animation", "running")
    import subprocess
    log_path = _ROOT / "state" / "run_log.jsonl"
    out_dir = PRODUCT / "demo"
    subprocess.run([sys.executable, str(_ROOT / "scripts" / "build_animation.py"),
                    "--log", str(log_path), "--out", str(out_dir)], cwd=_ROOT)
    git_ops.commit_and_push(PRODUCT, "demo: build-story animation (GIF/MP4)")
    runlog.log_git("push", "build-story animation")
    st.update(phase=5, status="complete")
    runlog.log_phase(5, "build_animation", "complete")
    save_state(st)
    print("\n*** Workflow complete. Product demo + build animation in roarpass/demo/. ***\n")


# ----------------------------- support stubs --------------------------------
# These wrap real tooling Claude Code fills in on the machine (headless browser, package mgrs).
# They are isolated so the orchestration logic above stays clean and testable.

def _git_init_if_needed():
    if not (PRODUCT / ".git").exists():
        import subprocess
        subprocess.run(["git", "init"], cwd=PRODUCT, capture_output=True)
        subprocess.run(["git", "branch", "-M", "main"], cwd=PRODUCT, capture_output=True)


def _git_msg(key: str, **kw) -> str:
    tmpl = yaml.safe_load((_ROOT / "config/git.yaml").read_text())["commit_policy"][key]
    return tmpl.format(**kw) if kw else tmpl


def _git_branch(key: str) -> str:
    return yaml.safe_load((_ROOT / "config/git.yaml").read_text())["branching"][key]


def _assemble_refined_requirements(chunks):
    parts = ["# RoarPass — Refined Requirements\n\n## Traceability\n",
             "| Chunk | PRD refs | Spec |\n|---|---|---|"]
    for c in chunks:
        parts.append(f"| {c['title']} | {', '.join(c.get('prd_refs', []))} | "
                     f"`docs/requirements/specs/{c['slug']}.md` |")
    parts.append("\n---\n")
    for c in chunks:
        sp = PRODUCT / f"docs/requirements/specs/{c['slug']}.md"
        if sp.exists():
            parts.append(f"\n# {c['title']}\n\n" + sp.read_text())
    (PRODUCT / "docs/requirements/REFINED_REQUIREMENTS.md").write_text("\n".join(parts))


def _assemble_design_readme(pages):
    parts = ["# RoarPass — Design Walkthrough (for your approval)\n",
             "Web + mobile-web designs for every feature. Screens are in `screens/`.\n",
             "## What we're asking you to approve\nThe IA, visual system, and per-page layouts "
             "below. Approve to proceed to implementation, or request changes.\n\n---\n"]
    for p in pages:
        slug = p["slug"]
        parts.append(f"## {p['title']}\n")
        parts.append(f"_Requirements: {', '.join(p.get('req_refs', []))}_\n")
        parts.append(f"![{slug} desktop](screens/{slug}-desktop.png)\n")
        parts.append(f"![{slug} mobile](screens/{slug}-mobile.png)\n\n")
    (PRODUCT / "docs/design/DESIGN_README.md").write_text("\n".join(parts))


def _capture_screens(pages):
    """Render each design HTML to PNG. Claude Code runs scripts/screenshot.py (headless browser)."""
    import subprocess
    script = _ROOT / "scripts" / "screenshot.py"
    (PRODUCT / "docs/design/screens").mkdir(parents=True, exist_ok=True)
    for p in pages:
        for vp in ("desktop", "mobile"):
            html = PRODUCT / f"apps/web/design/{p['slug']}/{vp}.html"
            out = PRODUCT / f"docs/design/screens/{p['slug']}-{vp}.png"
            if html.exists():
                subprocess.run([sys.executable, str(script), str(html), str(out), vp],
                               capture_output=True)


def _topo_waves(chunks):
    """Dependency-ordered waves; within a wave chunks are independent."""
    done, waves, remaining = set(), [], list(chunks)
    while remaining:
        wave = [c for c in remaining if set(c.get("dependencies", [])) <= done]
        if not wave:  # break cycles defensively
            wave = remaining
        waves.append(wave)
        done |= {c["slug"] for c in wave}
        remaining = [c for c in remaining if c not in wave]
    return waves


def _run_local_deploy_and_checks():
    import subprocess
    sh = PRODUCT / "scripts/deploy_local.sh"
    if sh.exists():
        subprocess.run(["bash", str(sh)], cwd=PRODUCT)


def _consolidate_test_report(results):
    lines = ["# RoarPass — Test Report\n", "| Area | Passed | Failed | Defects |", "|---|---|---|---|"]
    for r in results:
        try:
            j = json.loads(r["json"]) if r["json"] else {}
        except json.JSONDecodeError:
            j = {}
        s = j.get("summary", {})
        lines.append(f"| {r['id']} | {s.get('passed','?')} | {s.get('failed','?')} | "
                     f"{len(j.get('defects', []))} |")
    (PRODUCT / "docs/TEST_REPORT.md").write_text("\n".join(lines))


def _run_demo_capture():
    import subprocess
    spec = PRODUCT / "demo/capture_spec.json"
    script = _ROOT / "scripts/demo_capture.py"
    if spec.exists():
        subprocess.run([sys.executable, str(script), str(spec)], cwd=PRODUCT, capture_output=True)


# ----------------------------- dynamic mode ---------------------------------
def run_dynamic(prd_path: str, st: dict):
    """Fully dynamic: a planner agent designs the whole plan, the executor runs it.
    Gate placement is entirely the planner's choice; only secret-safety + prohibited-action
    rails are enforced by the executor."""
    print("== Dynamic mode: planning ==")
    runlog.log_phase(-1, "planner", "running")
    # bootstrap the product repo + PRD first (same safe scaffold as static phase 0)
    run_phase0(st)
    prd = (PRODUCT / "docs" / "RoarPass_PRD.md").read_text()
    scope = _WF.get("build_scope", {})
    plan_raw = agent.run_agent(
        "planner",
        f"BUILD SCOPE:\n{json.dumps(scope, indent=2)}\n\nPRD:\n{prd}\n\n"
        "Design the full build plan as JSON per your output contract.",
        phase=-1, agent_id="planner")
    plan = json.loads(agent.parse_json(plan_raw))
    (PRODUCT / "docs").mkdir(parents=True, exist_ok=True)
    (PRODUCT / "docs" / "GENERATED_PLAN.json").write_text(json.dumps(plan, indent=2))
    runlog.log_phase(-1, "planner", "complete")
    st["plan"] = plan
    st["completed_phases"] = st.get("completed_phases", [])
    save_state(st)
    result = executor.run_plan(plan, st)
    if result == "complete":
        notify.send_done_notification("RoarPass dynamic build complete.")


def resume_dynamic(st: dict, approve: bool, feedback: str = ""):
    gate.record_decision(approve, feedback)
    gate.clear_gate()
    runlog.log_gate("approved" if approve else "revising")
    st["status"] = "running"
    # the paused phase wasn't marked complete; executor will resume from it
    result = executor.run_plan(st["plan"], st)
    if result == "complete":
        notify.send_done_notification("RoarPass dynamic build complete.")


# ----------------------------- driver ---------------------------------------
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--prd")
    ap.add_argument("--resume", action="store_true")
    ap.add_argument("--approve", action="store_true")
    ap.add_argument("--revise")
    ap.add_argument("--revise-full", dest="revise_full")
    ap.add_argument("--status", action="store_true")
    ap.add_argument("--dynamic", action="store_true",
                    help="fully dynamic mode: a planner designs the whole plan, including gates")
    args = ap.parse_args()

    st = load_state()

    if args.status:
        print(json.dumps(st, indent=2))
        return

    if args.resume:
        if st.get("status") != "awaiting_approval":
            sys.exit("Nothing awaiting approval. Current state:\n" + json.dumps(st, indent=2))
        # dynamic resume if a generated plan exists
        if st.get("plan"):
            if args.approve:
                resume_dynamic(st, True)
            elif args.revise or args.revise_full:
                resume_dynamic(st, False, args.revise or args.revise_full)
            else:
                sys.exit("Use --approve or --revise \"...\" with --resume.")
            return
        # static resume
        if args.approve:
            gate.record_decision(True)
            gate.clear_gate()
            runlog.log_gate("approved")
            run_phase3(st)
            run_phase4(st)
            run_phase5(st)
        elif args.revise or args.revise_full:
            fb = args.revise or args.revise_full
            gate.record_decision(False, fb, full=bool(args.revise_full))
            gate.clear_gate()
            runlog.log_gate("revising")
            run_phase2(st, revise=fb, full=bool(args.revise_full))  # re-gates at the end
        else:
            sys.exit("Use --approve or --revise \"...\" with --resume.")
        return

    # fresh run
    if not args.prd:
        sys.exit("Provide --prd path on a fresh run.")
    runlog.reset()  # clear logs/transcripts only on a fresh run, not on --resume

    if args.dynamic:
        st = {"phase": -1, "status": "running", "chunks": None, "prd": args.prd, "dynamic": True}
        save_state(st)
        run_dynamic(args.prd, st)
        return

    st = {"phase": -1, "status": "init", "chunks": None, "prd": args.prd}
    save_state(st)
    run_phase0(st)
    run_phase1(st)
    run_phase2(st)  # halts at gate


if __name__ == "__main__":
    main()
